### ISSUE TITLE
[AWS] Guide to install Meilisearch using ECS

### ISSUE THREAD

**Issue by mabujaber** [meilisearch/cloud-providers#34]
it will be great if we get clear steps to install Meilisearch using ECS

**Comment by alallema** [comment]
As this issue has already been dealt with, I will close it.

**Comment by mabujaber** [comment]
Why did you depreciate this and close it?

**Comment by alallema** [comment]
I've deprecated the repo because we've moved all the cloud providers to this new repo I didn't deprecate the issue.
As we no longer offer as much maintenance on this repo we don't plan to change the scripts for the time being by adding new functionality, the aim being to keep the images as simple as possible, as there are far too many options that can be added via AWS. So I closed it
