### ISSUE TITLE
[gcp, aws, digitalocean] Ensure the env var `MEILI_SERVER_PROVIDER` is being sent

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/cloud-providers#47]
We need to ensure that we are setting our environment variable correctly.

Like we used to do in the cloud-scripts: https://github.com/meilisearch/cloud-scripts/blob/56a7c2630c1a508e5ad0c0ba1d8cfeb8d2fa9ae0/scripts/providers/gcp/cloud-config.yaml#L33

**Comment by alallema** [comment]
Yes, the variable is always set [here](https://github.com/meilisearch/cloud-providers/blob/d8a236faab4f8943ade1660a9085d86f741e6362/config/meilisearch.service#L7) then substituted [here](https://github.com/meilisearch/cloud-providers/blob/d8a236faab4f8943ade1660a9085d86f741e6362/meilisearch.pkr.hcl#L145).
The change is that now the names are no longer the same because we use the source denomination: `amazon-ebs`, `digitalocean`, `googlecompute`.
